import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';
import { Toaster } from '@/components/ui/sonner';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
// import { Lato } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import Providers from '@/components/layout/providers';
import { auth } from '@/lib/auth';
import RefreshButton from '@/components/refresh-button';
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: 'Akasia',
  description: 'Generated by create next app'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    // <html lang="en" suppressHydrationWarning>
    //   <body className={` antialiased`}>
    //     <nav className="px-8 py-4">
    //       <div className="flex items-center space-x-4">
    //         <Link href={"/"}>Home</Link>
    //         <Link href={"/pemasukan"}>Pemasukan</Link>
    //         <Link href={"/pengeluaran"}>Pengeluaran</Link>
    //       </div>
    //     </nav>
    //     {children}
    //     <Toaster richColors />
    //   </body>
    // </html>
    <html
      lang='en'
      // className={`${lato.className}`}
      suppressHydrationWarning
    >
      <body className={'overflow-hidden'}>
        <NextTopLoader showSpinner={false} />
        <NuqsAdapter>
          <Providers session={session}>
            <Toaster richColors />
            {children}
          </Providers>
        </NuqsAdapter>
        <RefreshButton />
      </body>
    </html>
  );
}
