import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <nav className="px-8 py-4">
          <div className="flex items-center space-x-4">
            <Link href={"/"}>Home</Link>
            <Link href={"/pemasukan"}>Pemasukan</Link>
            <Link href={"/pengeluaran"}>Pengeluaran</Link>
          </div>
        </nav>
        {children}
        <Toaster richColors />
      </body>
    </html>
  );
}
